# Generated by Django 5.0.6 on 2024-06-20 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_code_alter_company_strength_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Company code not in correct format.', regex='[a-z][a-z][0-9][0-9][en]')]),
        ),
    ]
